### ISSUE TITLE
Does not work in Nightly (45.0a1)

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-browser-addon#39]
I tested as described on https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox, but actually even without disabling the shims, LTFx doesn't work in version 45.0a1, i.e. it won't appear in the context menu nor does the shortcut (Ctrl-Return) cause a check in a textarea.

    console.error: languagetoolfx: 
    Message: TypeError: window.getSelection is not a function
    Stack:
      addSelectionListener@resource://gre/modules/commonjs/sdk/selection.js:345:19

**Comment by danielnaber** [comment]
Seems to be caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1060695. Removing `var selection=require("sdk/selection");` and its uses (and thus the feature to work on selected text) makes it work again.

**Comment by danielnaber** [comment]
Cannot reproduce anymore.

**Comment by danielnaber** [comment]
While https://bugzilla.mozilla.org/show_bug.cgi?id=1060695 is still open, LTFx works for me with Firefox 45.
